Repository go-vela/pkg-executor, pull requests merged in 2020-04, with the labels that each got.

#12 feat: enable setting hostname
  executor/executor_test.go
  executor/linux/linux.go
  executor/linux/linux_test.go
  executor/linux/opts.go
  executor/linux/opts_test.go
  executor/setup.go
  executor/setup_test.go
Labels: feature

#13 feat(linux): add helpers for loading values
  executor/linux/build.go
  executor/linux/service.go
  executor/linux/service_test.go
  executor/linux/stage.go
  executor/linux/step.go
  executor/linux/step_test.go
Labels: feature

#17 docs(executor): add pkg.go.dev links
  executor/executor.go
  executor/flags.go
  executor/setup.go
Labels: enhancement

#18 chore: update for v0.4.0-rc1
  executor/linux/service.go
  executor/linux/step.go
  go.mod
  go.sum
Labels: dependencies

#19 refactor(linux): use AppendData() library.Log func
  executor/flags.go
  executor/linux/build.go
  executor/linux/service.go
  executor/linux/stage.go
  executor/linux/step.go
Labels: enhancement

#20 refactor(linux): update logging setup
  executor/linux/build.go
  executor/linux/linux.go
  executor/linux/opts.go
  executor/linux/service.go
  executor/linux/stage.go
  executor/linux/step.go
Labels: enhancement

#21 docs(linux): add comments and pkg.go.dev links
  executor/linux/build.go
  executor/linux/secret.go
  executor/linux/service.go
  executor/linux/stage.go
  executor/linux/step.go
Labels: enhancement

#22 fix(linux): update timestamps for resources
  executor/linux/build.go
  executor/linux/service.go
  executor/linux/service_test.go
  executor/linux/stage_test.go
  executor/linux/step.go
  executor/linux/step_test.go
Labels: bug

#23 fix(linux): update detached containers
  executor/linux/opts.go
  executor/linux/service.go
  executor/linux/step.go
Labels: bug

#25 fix: update status logic for ruleset
  executor/linux/build.go
  executor/linux/build_test.go
  go.mod
  go.sum
Labels: bug

#27 chore: update dependencies for v0.4.0-rc2
  go.mod
  go.sum
Labels: dependencies

#26 fix: update to ruleset match logic for status checks
  executor/linux/build.go
  executor/linux/stage.go
  executor/linux/stage_test.go
  executor/linux/step.go
  go.mod
  go.sum
Labels: bug

#28 chore: update version to v0.4.0-rc3
  go.mod
  go.sum
Labels: dependencies

#29 chore(linux): add extra service env vars
  executor/linux/service.go
Labels: enhancement
