Repository go-vela/pkg-executor, pull requests merged in 2020-05, with the labels that each got.

#30 chore: update dependencies to v0.4.0
  go.mod
  go.sum
Labels: dependencies

#32 fix: update ruleset status logic
  executor/linux/api_test.go
  executor/linux/build.go
  executor/linux/build_test.go
  executor/linux/linux_test.go
  executor/linux/opts_test.go
  executor/linux/secret_test.go
  executor/linux/service_test.go
  executor/linux/stage.go
  executor/linux/stage_test.go
  executor/linux/step_test.go
Labels: bug

#33 chore: update dependencies for release
  go.mod
  go.sum
Labels: dependencies

#35 enhancement: swap regards for new container execute
  executor/linux/build.go
  executor/linux/stage.go
  go.mod
  go.sum
Labels: enhancement

#36 chore: update for patch release v0.4.2
  go.mod
  go.sum
Labels: dependencies

#37 chore: update for patch release v0.4.3
  go.mod
  go.sum
Labels: dependencies

#38 docs: divert bugs and features to community
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/not_here.md
Labels: enhancement
