Repository go-vela/pkg-executor, pull requests merged in 2020-07, with the labels that each got.

#42 ci: refactor Makefile. improve linter setup. upgrade deps.
  .github/workflows/build.yml
  .github/workflows/release.yml
  .github/workflows/reviewdog.yml
  .github/workflows/test.yml
  .github/workflows/validate.yml
  .golangci.yml
  Makefile
  codecov.yml
  go.mod
  go.sum
Labels: dependencies, enhancement

#41 feat: add plugin pattern for secrets look up
  .golangci.yml
  executor/engine.go
  executor/linux/build.go
  executor/linux/build_test.go
  executor/linux/linux.go
  executor/linux/linux_test.go
  executor/linux/secret.go
  executor/linux/secret_test.go
  executor/linux/step.go
  executor/linux/testdata/build/empty.yml
  executor/linux/testdata/build/secrets/basic.yml
  executor/linux/testdata/build/secrets/img_ignorenotfound.yml
  executor/linux/testdata/build/secrets/img_notfound.yml
  executor/linux/testdata/build/secrets/name_notfound.yml
  executor/linux/testdata/build/services/basic.yml
  executor/linux/testdata/build/services/img_ignorenotfound.yml
  executor/linux/testdata/build/services/img_notfound.yml
  executor/linux/testdata/build/services/name_notfound.yml
  executor/linux/testdata/build/stages/basic.yml
  executor/linux/testdata/build/stages/img_ignorenotfound.yml
  executor/linux/testdata/build/stages/img_notfound.yml
  executor/linux/testdata/build/stages/name_notfound.yml
  executor/linux/testdata/build/steps/basic.yml
  executor/linux/testdata/build/steps/img_ignorenotfound.yml
  executor/linux/testdata/build/steps/img_notfound.yml
  executor/linux/testdata/build/steps/name_notfound.yml
  executor/linux/testdata/secret/basic.yml
  executor/linux/testdata/secret/name_notfound.yml
  go.mod
  go.sum
Labels: feature

#43 fix: update the init logs to be more verbose
  executor/linux/build.go
  executor/linux/stage.go
  go.mod
  go.sum
Labels: enhancement

#44 chore: update go mod for v0.5.0-rc1
  go.mod
  go.sum
Labels: dependencies
