Repository go-vela/pkg-executor, pull requests merged in 2021-02, with the labels that each got.

#117 fix(local): step output for stages
  executor/local/step.go
  executor/local/step_test.go
Labels: bug

#118 fix: wrap defers in function shell
  executor/linux/build.go
  executor/linux/service.go
  executor/linux/step.go
  executor/local/build.go
  executor/local/service.go
  executor/local/step.go
Labels: bug

#119 feat(internal): add step.LoadInit() function
  executor/linux/build.go
  executor/linux/step.go
  executor/local/build.go
  executor/local/step.go
  internal/step/load.go
  internal/step/load_test.go
Labels: feature

#122 chore: linter setup and fixes, doc changes
  .github/CONTRIBUTING.md
  .golangci.yml
  cmd/vela-executor/resource.go
  executor/context.go
  executor/context_test.go
  executor/linux/build.go
  executor/linux/build_test.go
  executor/linux/linux.go
  executor/linux/secret.go
  executor/linux/service.go
  executor/linux/stage_test.go
  executor/linux/step.go
  executor/local/build.go
  executor/local/local_test.go
Labels: enhancement

#123 chore: upgrade go-vela deps on v0.7.0
  go.mod
  go.sum
Labels: dependencies

#125 fix(internal): ignore build errors in canceled state
  executor/linux/api.go
  executor/local/api.go
  internal/build/snapshot.go
  internal/build/upload.go
Labels: bug

#126 feat: set service/step/stage status as canceled when cancelling a build
  executor/linux/api.go
  executor/linux/service.go
  executor/linux/stage.go
  executor/local/api.go
  executor/local/stage.go
  internal/service/snapshot.go
  internal/step/snapshot.go
Labels: feature

#127 fix: use fresh context for capturing container logs
  executor/linux/service.go
  executor/linux/step.go
  executor/local/service.go
  executor/local/step.go
Labels: bug

#124 test(linux): overhaul test suite
  executor/linux/build_test.go
  executor/linux/linux_test.go
  executor/linux/service_test.go
  executor/linux/stage_test.go
  executor/linux/step_test.go
Labels: enhancement

#133 refactor(internal): switch to container.MergeEnv()
  internal/service/environment.go
  internal/step/environment.go
Labels: enhancement
